language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lauren-mak
  password:
    secure: kRTzVhC1ZKJL2gI1cwFEFwRcDNXLRExBajoAiDvSR+Oc4sHgb+DN5OQdZfc1o74kmlYmOJJXpq7stwH3AWxNGBY53OCoupJoezOGslhvKquags/F1LpWsVDLsPSOW8PWod+QkX0SX3iLxPUHP73Cx+3N3P/rYCqM6ul7wVC1/GWpA6HerS+B8ZCs6DvImhX/yhouxh0xn7B2H7AQPs5XrNDRgjxZdczVRt9Z6dAPrpdyleIS8YtvdH0zNlPVc8M+J4IqVZoAn1uRrdbqyaYwiBc5mGeC5ZGabSBc8Q5e2tv4qI7Mz+2uf2kOx2X47omkH3x7ueAycX2Lrd2gjNGJHrrpzwwW7CwrqUVWefwqdqJSrRGAWwnuv4yB9iHWUdsLo5TIoPt57JvVIgOwsaatHIX26zvFKncadpgzGDL+SHEQNGCDDry73Zu2juzf5aTGGOnZhH+Eg/Hd2HpZl09wxr9uqFLI4MH/9aiKqqzDRNDzMAbRWNXiiLoHAdm2KDkyfZ9uZf9i6iQIIOFPAV6YIUAUtD8apW+skZGCd3+O+Al13JIsvkN0nvqoWJSjSfjqhjknyMbtBU4f4uZSIRZeRpY0p4Ay8Gf855/DrjVRPkiu2kdn9pllrvEnF1jN/vaEx9qOr6KT0+KONfqcQD86XI6NFowrpxYt5/woIF+P+GU=
  on:
    tags: true
    repo: lauren-mak/cap2_assembly
    python: 3.8
